import type { CSSProperties } from "react";

/** Co-located styles for the agent editor's Skills tab. */
export const s = {
  wrap: { maxWidth: 960 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "7px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 260,
  } satisfies CSSProperties,
  filterIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 16 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (bound: boolean, enabled: boolean, dragging: boolean, over: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid " + (over ? "var(--accent)" : bound ? "var(--border-strong)" : "var(--border)"),
    background: bound ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: dragging ? 0.4 : enabled ? 1 : 0.6,
    transition: "border-color .1s",
  }),
  handle: (active: boolean): CSSProperties => ({
    color: active ? "var(--text-muted)" : "transparent",
    cursor: active ? "grab" : "default",
    display: "inline-flex",
    flexShrink: 0,
    userSelect: "none",
  }),
  name: { fontSize: 13, fontWeight: 600, flex: 1, minWidth: 0, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" } satisfies CSSProperties,
  description: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" } satisfies CSSProperties,
  text: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  arrows: { display: "inline-flex", gap: 2 } satisfies CSSProperties,
  arrowBtn: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 5,
    color: disabled ? "var(--border-strong)" : "var(--text-muted)",
    cursor: disabled ? "default" : "pointer",
    display: "inline-flex",
    padding: 3,
  }),
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "12px 0" } satisfies CSSProperties,
  checkbox: (checked: boolean, disabled: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    flexShrink: 0,
    borderRadius: 4,
    border: "1.5px solid " + (checked ? "var(--accent)" : "var(--border-strong)"),
    background: checked ? "var(--accent)" : "transparent",
    display: "grid",
    placeItems: "center",
    padding: 0,
    cursor: disabled ? "default" : "pointer",
    opacity: disabled ? 0.6 : 1,
  }),
} as const;
