import type { CSSProperties } from "react";

/** Co-located styles for StatsTab (tiles + agents card, per the design). */
export const s = {
  wrap: { maxWidth: 1100, display: "flex", flexDirection: "column", gap: 20 } satisfies CSSProperties,
  tiles: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 18 } satisfies CSSProperties,
  tile: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "18px 20px 22px",
    minHeight: 132,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  tileHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, minHeight: 44 } satisfies CSSProperties,
  tileLabel: {
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tileValueRow: { display: "flex", alignItems: "baseline", gap: 8 } satisfies CSSProperties,
  tileValue: { fontSize: 34, fontWeight: 700, lineHeight: 1, color: "var(--text-primary)" } satisfies CSSProperties,
  tileUnit: { fontSize: 15, fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,
  tileNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  cards: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)", gap: 18 } satisfies CSSProperties,
  card: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "16px 20px 20px",
  } satisfies CSSProperties,
  cardHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 14,
  } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginBottom: 8,
    textDecoration: "none",
    color: "inherit",
  } satisfies CSSProperties,
  agentIcon: {
    width: 28,
    height: 28,
    borderRadius: 7,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  agentName: { flex: 1, fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  open: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  none: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
