import type { CSSProperties } from "react";

export const s = {
  header: {
    position: "sticky",
    top: "var(--pr-sticky-offset, 0px)",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "var(--bg-primary)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  toggle: (empty: boolean): CSSProperties => ({
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    background: "transparent",
    border: "none",
    color: "var(--text-primary)",
    cursor: empty ? "default" : "pointer",
    opacity: empty ? 0.6 : 1,
    textAlign: "left",
  }),
  collapseAll: (empty: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 6,
    marginRight: 8,
    background: "transparent",
    border: "none",
    borderRadius: 5,
    color: "var(--text-muted)",
    cursor: empty ? "default" : "pointer",
    opacity: empty ? 0.4 : 1,
  }),
  square: (color: string): CSSProperties => ({
    width: 10,
    height: 10,
    borderRadius: 2,
    background: color,
    flexShrink: 0,
  }),
  label: { fontSize: 13.5, fontWeight: 700 } satisfies CSSProperties,
  description: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  right: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 12,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  findings: { color: "var(--crit)", fontWeight: 600 } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  body: { paddingTop: 10 } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(90deg)" : "none",
    transition: "transform .12s",
    flexShrink: 0,
  }),
} as const;
